TeapotioBaseUserBundle_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: TeapotioBaseUserBundle:Default:index }
TeapotioBaseUserBundle_login:
    pattern:   /login/
    defaults:  { _controller: TeapotioBaseUserBundle:Security:login }
TeapotioBaseUserBundle_signup:
    pattern:   /signup/
    defaults:  { _controller: TeapotioBaseUserBundle:Registration:signup }
TeapotioBaseUserBundle_forgotPassword:
    pattern:   /forgot-password/
    defaults:  { _controller: TeapotioBaseUserBundle:Account:forgotPassword }
TeapotioBaseUserBundle_resetPassword:
    pattern:   /reset-password/
    defaults:  { _controller: TeapotioBaseUserBundle:Account:resetPassword }
TeapotioBaseUserBundle_login_check:
    pattern:   /login-check/
TeapotioBaseUserBundle_logout:
    pattern:   /logout/