parameters:
    teapotio_user.user_service.class: Teapotio\Base\UserBundle\Service\UserService
    teapotio_user.user_group_service.class: Teapotio\Base\UserBundle\Service\UserGroupService

    teapotio_user.user_repository.class: 'TeapotioBaseUserBundle:User'
    teapotio_user.user_group_repository.class: 'TeapotioBaseUserBundle:UserGroup'
    teapotio_user.user_token_repository.class: 'TeapotioBaseUserBundle:UserToken'

services:
    teapotio.user:
        class: %teapotio_user.user_service.class%
        arguments: [@service_container]
    teapotio.user.group:
        class: %teapotio_user.user_group_service.class%
        arguments: [@service_container]
